export type TechIconProps = {
  size?: string;
};
export {CSharpIcon} from './CSharpIcon';
export {CssIcon} from './CssIcon';
export {ExpressJsIcon} from './ExpressJsIcon';
export {GraphQLIcon} from './GraphQLIcon';
export {HibernateIcon} from './HibernateIcon';
export {HtmlIcon} from './HtmlIcon';
export {JavaIcon} from './JavaIcon';
export {JavascriptIcon} from './JavascriptIcon';
export {MongoIcon} from './MongoIcon';
export {NetIcon} from './NetIcon';
export {NextJsIcon} from './NextJsIcon';
export {NodeJsIcon} from './NodeJsIcon';
export {PostgreIcon} from './PostgreIcon';
export {PrismaIcon} from './PrismaIcon';
export {ReactIcon} from './ReactIcon';
export {ReduxIcon} from './ReduxIcon';
export {SequelizeIcon} from './SequelizeIcon';
export {SpringIcon} from './SpringIcon';
export {TypescriptIcon} from './TypescriptIcon';
export {AspNetIcon} from './AspNetIcon';
