import React from 'react';
import {Key, useRef, useState} from 'react';
import {CSSTransition, SwitchTransition} from 'react-transition-group';
import Header from 'components/header/Header';
import NavBar from 'components/nav-bar/NavBar';
import Footer from 'components/footer/Footer';
import TechsAndInfo from 'components/portfolioSections/techs-and-info/TechsAndInfo';
import Projects from 'components/portfolioSections/projects/Projects';
import Education from 'components/portfolioSections/education/Education';
import Experiences from 'components/portfolioSections/experiences/Experiences';
import Skills from 'components/portfolioSections/skills/Skills';
import CircleButton from 'components/common/button/CircleButton';
import styles from 'styles/Home.module.css';
import Head from 'next/head';
import {InferGetStaticPropsType} from 'next';
import portfolioService from '../services/portfolioService';

const sectionsNames = ['Who am I', 'Projects', 'Experiences', 'My education', 'My skills'];
const Home: React.FC<InferGetStaticPropsType<typeof getStaticProps>> = ({
  user,
  educations,
  experiences,
  projects,
  skills,
  techs,
}) => {
  const sections = [
    <TechsAndInfo user={user} techs={techs} />,
    <Projects projects={projects} />,
    <Experiences experiences={experiences} />,
    <Education educations={educations} />,
    <Skills skills={skills} />,
  ];
  const [index, setIndex] = useState(0);
  const [state, setState] = useState(true);

  const section = useRef<HTMLDivElement>(null);

  function scrollIntoView(i: number) {
    section.current?.scrollIntoView();
    triggerAnimation(i);
  }
  function triggerAnimation(i: number) {
    if (index === i) return;
    setState(ps => !ps);
    setIndex(i);
  }
  const previousSection = () => {
    triggerAnimation(!index ? sections.length - 1 : index - 1);
  };
  const nextSection = () => {
    triggerAnimation(index === sections.length - 1 ? 0 : index + 1);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <script src='https://kit.fontawesome.com/8f51ab7548.js' crossOrigin='anonymous' />
      </Head>
      <NavBar user={user} />
      <Header user={user} />
      <main className={styles.main}>
        <div>
          <Arrow action={previousSection} />
          <Arrow action={nextSection} />
        </div>
        <div className={styles.bottomPart}>
          <SectionLinks index={index} triggerAnimation={triggerAnimation} />
          <Sections ref={section} state={state.toString()} sections={sections} index={index} />
        </div>
        <Footer sections={sectionsNames} setLinkIndex={scrollIntoView} />
      </main>
    </>
  );
};

interface ArrowProps {
  action: () => void;
}

const Arrow: React.FC<ArrowProps> = ({action}) => (
  <div className={styles.arrowTrack}>
    <div>
      <CircleButton action={action}>
        <i className='fa-solid fa-arrow-right'></i>
      </CircleButton>
    </div>
  </div>
);

interface SectionLinksProps {
  index: number;
  triggerAnimation: (i: number) => void;
}

const SectionLinks: React.FC<SectionLinksProps> = ({index, triggerAnimation}) => (
  <div className={styles.sectionLinks}>
    {sectionsNames.map((sn, i) => (
      <span
        key={sn}
        onClick={() => triggerAnimation(i)}
        className={index === i ? styles.clickedSectionLink : undefined}
      >
        {sn}
      </span>
    ))}
  </div>
);

interface SectionsProps {
  index: number;
  state: Key | null | undefined;
  sections: JSX.Element[];
}

const Sections = React.forwardRef<HTMLDivElement, SectionsProps>(({index, state, sections}, ref) => (
  <div ref={ref} className={styles.sectionsContainer}>
    <SwitchTransition>
      <CSSTransition
        key={state}
        addEndListener={(node, done) => {
          node.addEventListener('transitionend', done, false);
        }}
        classNames='fade'
      >
        {sections[index]}
      </CSSTransition>
    </SwitchTransition>
  </div>
));

export const getStaticProps = async () => {
  try {
    const educations = await portfolioService.getEducations();
    console.log(educations);
    const experiences = await portfolioService.getExperiences();
    console.log(experiences);
    const projects = await portfolioService.getProjects();
    console.log(projects);
    const skills = await portfolioService.getSkills();
    console.log(skills);
    const techs = await portfolioService.getTechs();
    console.log(techs);
    const users = await portfolioService.getUsers();
    return {
      props: {
        educations,
        experiences,
        projects,
        skills,
        techs,
        user: users?.[0],
      },
      revalidate: 300,
    };
  } catch (err) {
    console.log(err);
  }
  return {props: {}};
};

export default Home;
